### ISSUE TITLE
Conflicts text colors in tailwind-merge

### ISSUE THREAD

**Issue by andrilla-francis** [designbycode/tailwindcss-text-shadow#1]
This appears to conflict with text colors in tailwind-merge. How are we intended to fix this? I've played around with creating a custom `twMerge()` with `extendTailwindMerge` but can't seem to get it to work right.

#### Component

```
// components/link.tsx

import type { LinkProps } from '@/typings/components'
import { twMerge } from 'tailwind-merge'

export default function Link({ children, className, href }: LinkProps) {
  const defaultClasses = 'text-blue-500'

  return (
    <a href={href} className={twMerge(defaultClasses, className)}>{children}</a>
  )
}
```

#### Input

```
import Link from '@/components/link'

export default function Page() {
  return (
    <Link href='https://andrilla.net' className='text-shadow-lg text-shadow-red-500'>Website</Link>
  )
}
```

#### Intended Output

`<a href='https://andrilla.net' class='text-blue-500 text-shadow-lg text-shadow-red-500'>Website</a>`

#### Actual Output

`<a href='https://andrilla.net' class='text-shadow-lg'>Website</a>`

**Comment by claudemyburgh** [comment]
The twMerge see it as a text utility so I updated the code to allow you to change the class name from `text-shadow` to `ts-shadow` or what ever you want. change the following in `tailwind.config`  file.
```js
// tailwind.config.js
module.exports = {
    theme: {
        prefix: 'ts',
    },
}
```

```html
 <div class="ts-lg ts-indigo-500"></div>
```

**Comment by claudemyburgh** [comment]
See solution above
